export type LanguageCode = 'en' | 'fr' | 'ja' | 'es' | 'de' | 'it'

export interface LanguageOption {
  code: LanguageCode
  name: string
  flag: string
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
]

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    toc: 'Table of Contents',
    search: 'Search text…',
    cart: 'Shopping Bag',
    audio: 'Listen to Narration',
    share: 'Share Edition',
    qr: 'Scan QR Code',
    fullscreen: 'Fullscreen',
    single: 'Single Page',
    spread: 'Two-Page Spread',
    notes: 'Review Notes',
    unlock: 'Unlock full edition',
    checkout: 'Checkout Now',
    add_to_cart: 'Add to Cart',
    page: 'Page',
    of: 'of',
  },
  fr: {
    toc: 'Table des Matières',
    search: 'Rechercher…',
    cart: 'Panier',
    audio: 'Écouter la Narration',
    share: 'Partager',
    qr: 'Code QR',
    fullscreen: 'Plein Écran',
    single: 'Page Simple',
    spread: 'Double Page',
    notes: 'Notes de Relecture',
    unlock: 'Débloquer l’Édition',
    checkout: 'Commander',
    add_to_cart: 'Ajouter au Panier',
    page: 'Page',
    of: 'sur',
  },
  ja: {
    toc: '目次',
    search: 'テキスト検索…',
    cart: 'ショッピングバッグ',
    audio: '音声ナレーション',
    share: '共有',
    qr: 'QRコード',
    fullscreen: '全画面表示',
    single: '単一ページ',
    spread: '見開き表示',
    notes: '校正メモ',
    unlock: '全編ロック解除',
    checkout: '今すぐ購入',
    add_to_cart: 'バッグに追加',
    page: 'ページ',
    of: '/',
  },
  es: {
    toc: 'Índice de Contenido',
    search: 'Buscar texto…',
    cart: 'Bolsa de Compras',
    audio: 'Escuchar Narración',
    share: 'Compartir',
    qr: 'Código QR',
    fullscreen: 'Pantalla Completa',
    single: 'Página Simple',
    spread: 'Doble Página',
    notes: 'Notas de Revisión',
    unlock: 'Desbloquear Edición',
    checkout: 'Comprar Ahora',
    add_to_cart: 'Añadir a la Bolsa',
    page: 'Página',
    of: 'de',
  },
  de: {
    toc: 'Inhaltsverzeichnis',
    search: 'Suchen…',
    cart: 'Warenkorb',
    audio: 'Audio-Vorlesen',
    share: 'Teilen',
    qr: 'QR-Code',
    fullscreen: 'Vollbild',
    single: 'Einzelseite',
    spread: 'Doppelseite',
    notes: 'Korrektur-Notizen',
    unlock: 'Ausgabe freischalten',
    checkout: 'Zur Kasse',
    add_to_cart: 'In den Warenkorb',
    page: 'Seite',
    of: 'von',
  },
  it: {
    toc: 'Indice dei Contenuti',
    search: 'Cerca…',
    cart: 'Carrello',
    audio: 'Ascolta Narrazione',
    share: 'Condividi',
    qr: 'Codice QR',
    fullscreen: 'Schermo Intero',
    single: 'Pagina Singola',
    spread: 'Doppia Pagina',
    notes: 'Note di Revisione',
    unlock: 'Sblocca Edizione',
    checkout: 'Acquista Ora',
    add_to_cart: 'Aggiungi al Carrello',
    page: 'Pagina',
    of: 'di',
  },
}

export function getTranslation(lang: LanguageCode, key: string): string {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key
}
